AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Save form to S3 \n"
Parameters:
  AppStage:
    Type: String
    Default: api
    Description: API Gateway stage, used as a prefix for the endpoint URLs
    AllowedPattern: ^[A-Za-z]+$
    MaxLength: 10
    MinLength: 1
    ConstraintDescription: 1-10 Latin letters
Resources:
  UploadS3Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      SamResourceId: UploadS3Bucket
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: AppStage
    Metadata:
      SamResourceId: WebApi
  ShowFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://s3lambdapool/284d90390834ac75dffcf0242d4c6834
      Handler: show-form.lambdaHandler
      Runtime: nodejs16.x
      Events:
        ShowForm:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: WebApi
    Metadata:
      SamResourceId: ShowFormFunction
  ProcessFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://s3lambdapool/284d90390834ac75dffcf0242d4c6834
      Handler: process-form.lambdaHandler
      Runtime: nodejs16.x
      Events:
        SubmitForm:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId:
              Ref: WebApi
      Environment:
        Variables:
          UPLOAD_S3_BUCKET:
            Ref: UploadS3Bucket
      Policies:
      - S3FullAccessPolicy:
          BucketName:
            Ref: UploadS3Bucket
    Metadata:
      SamResourceId: ProcessFormFunction
Outputs:
  UserFormApi:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/
  UploadBucket:
    Description: S3 Bucket for user information
    Value:
      Ref: UploadS3Bucket
